server:
  port: 7002

eureka:
  instance:
    hostname: www.eureka7002.com #服务端名字
  client:
    register-with-eureka: false #表示是否向eureka注册中心注册自己
    fetch-registry: false #如果为false则表示自己为注册中心
    service-url: #注册中间交互地址（监控页面）
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://www.eureka7001.com:7001/eureka/,http://www.eureka7003.com:7003/eureka/
